// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/calculate-zakah": {
            "post": {
                "description": "Takes user assets and liabilities, converts currency, and calculates Zakah due.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calculator"
                ],
                "summary": "Calculate Zakah",
                "parameters": [
                    {
                        "description": "Calculation Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CalculationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.CalculationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.CalculationRequest": {
            "type": "object",
            "properties": {
                "business_assets": {
                    "type": "number"
                },
                "cash": {
                    "type": "number"
                },
                "currency": {
                    "type": "string"
                },
                "gold_grams": {
                    "type": "number"
                },
                "liabilities": {
                    "type": "number"
                },
                "silver_grams": {
                    "type": "number"
                }
            }
        },
        "types.CalculationResponse": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "local_currency": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "nisab_threshold": {
                    "type": "number"
                },
                "total_assets": {
                    "type": "number"
                },
                "zakah_payable": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Zakah Calculator API",
	Description:      "A clean Zakah calculator API with currency conversion.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
